/*
	Copyright 2023 Mohamed Shalan

	Author: Mohamed Shalan (mshalan@aucegypt.edu)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define DMAC_BASE				0x00000000

#define	DMAC_CONTROL_REG_ADDR		(DMAC_BASE+0x0)
#define	DMAC_STATUS_REG_ADDR		(DMAC_BASE+0x4)
#define	DMAC_SADDR_REG_ADDR		(DMAC_BASE+0x8)
#define	DMAC_DADDR_REG_ADDR		(DMAC_BASE+0xc)
#define	DMAC_COUNT_REG_ADDR		(DMAC_BASE+0x10)
#define	DMAC_SWTRIG_REG_ADDR		(DMAC_BASE+0x14)

#define DMAC_CONTROL_REG_EN		0
#define DMAC_CONTROL_REG_EN_LEN	1
#define DMAC_CONTROL_REG_TRIG		8
#define DMAC_CONTROL_REG_TRIG_LEN	4
#define DMAC_CONTROL_REG_STYPE		16
#define DMAC_CONTROL_REG_STYPE_LEN	2
#define DMAC_CONTROL_REG_SAI		18
#define DMAC_CONTROL_REG_SAI_LEN	1
#define DMAC_CONTROL_REG_DTYPE		24
#define DMAC_CONTROL_REG_DTYPE_LEN	2
#define DMAC_STATUS_REG_DONE		0
#define DMAC_STATUS_REG_DONE_LEN	1
#define DMAC_SWTRIG_REG_SWTRIG		0
#define DMAC_SWTRIG_REG_SWTRIG_LEN	1

volatile unsigned int * dmac_CONTROL_REG	= (volatile unsigned int *) DMAC_CONTROL_REG_ADDR;
volatile unsigned int * dmac_SADDR_REG	= (volatile unsigned int *) DMAC_SADDR_REG_ADDR;
volatile unsigned int * dmac_DADDR_REG	= (volatile unsigned int *) DMAC_DADDR_REG_ADDR;
volatile unsigned int * dmac_COUNT_REG	= (volatile unsigned int *) DMAC_COUNT_REG_ADDR;
volatile unsigned int * dmac_SWTRIG_REG	= (volatile unsigned int *) DMAC_SWTRIG_REG_ADDR;
