/*
	Copyright 2020 Mohamed Shalan

	Author: Mohamed Shalan (mshalan@aucegypt.edu)

	This file is auto-generated by wrapper_gen.py on 2023-11-27

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#ifndef IO_TYPES
#define IO_TYPES
#define   __R     volatile const unsigned int
#define   __W     volatile       unsigned int
#define   __RW    volatile       unsigned int
#endif

#define MS_DMAC_AHBL_CONTROL_REG_EN		0
#define MS_DMAC_AHBL_CONTROL_REG_EN_LEN	1
#define MS_DMAC_AHBL_CONTROL_REG_TRIG		8
#define MS_DMAC_AHBL_CONTROL_REG_TRIG_LEN	4
#define MS_DMAC_AHBL_CONTROL_REG_STYPE		16
#define MS_DMAC_AHBL_CONTROL_REG_STYPE_LEN	2
#define MS_DMAC_AHBL_CONTROL_REG_SAI		18
#define MS_DMAC_AHBL_CONTROL_REG_SAI_LEN	3
#define MS_DMAC_AHBL_CONTROL_REG_DTYPE		24
#define MS_DMAC_AHBL_CONTROL_REG_DAI		26
#define MS_DMAC_AHBL_CONTROL_REG_DAI_LEN	3
#define MS_DMAC_AHBL_CONTROL_REG_DTYPE_LEN	2
#define MS_DMAC_AHBL_STATUS_REG_DONE		0
#define MS_DMAC_AHBL_STATUS_REG_DONE_LEN	1
#define MS_DMAC_AHBL_SWTRIG_REG_SWTRIG		0
#define MS_DMAC_AHBL_SWTRIG_REG_SWTRIG_LEN	1

typedef struct _MS_DMAC_AHBL_TYPE_ {
	__RW	control;
	__R 	status;
	__RW	saddr;
	__RW	daddr;
	__RW	count;
	__RW	swtrig;
	__R 	reserved[954];
	__W 	icr;
	__R 	ris;
	__RW	im;
	__R 	mis;
} MS_DMAC_AHBL_TYPE;
